#!/usr/bin/env python3
import os
import sys
import json
from datetime import datetime
from pathlib import Path

def generate_markdown_report(stage_name, status, logs_dir, output_file):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = [
        f"# NasTech Branding Pipeline Report - {stage_name}",
        f"**Timestamp**: {timestamp}",
        f"**Status**: {'✅ SUCCESS' if status == 'success' else '❌ FAILED'}",
        "",
        "## Stage Details",
        f"This report documents the results of the **{stage_name}** stage in the branding transformation pipeline.",
        "",
        "## Execution Summary",
    ]
    
    # Try to find log files in the logs directory
    log_files = list(Path(logs_dir).glob("*.log"))
    if not log_files:
        report.append("No detailed log files found for this stage.")
    else:
        for log_file in log_files:
            report.append(f"### Log: {log_file.name}")
            report.append("```text")
            try:
                with open(log_file, "r") as f:
                    content = f.read()
                    # Truncate if too long
                    if len(content) > 5000:
                        content = content[:5000] + "\n... (truncated)"
                    report.append(content)
            except Exception as e:
                report.append(f"Error reading log file: {e}")
            report.append("```")
            report.append("")

    report.append("---")
    report.append("_Generated by NasTech Pipeline Orchestrator_")
    
    with open(output_file, "w") as f:
        f.write("\n".join(report))
    
    print(f"Report generated at {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: python3 generate-report.py <stage_name> <status> <logs_dir> <output_file>")
        sys.exit(1)
        
    generate_markdown_report(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
